from setuptools import setup

INSTALL_REQUIRES = [
    'setuptools',
    'wheel',
    'pkginfo',
    'jinja2',
    'colorama',
    'attrs>=17',
    'packaging',
    'pyyaml'
]

version_template = """\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = {version!r}
"""

setup(setup_requires=['setuptools-scm', 'setuptools>=38.6.0'],
      use_scm_version={
          'write_to': 'src/_wheel2deb/version.py',
          'write_to_template': version_template},
      package_dir={'': 'src'},
      install_requires=INSTALL_REQUIRES,
      include_package_data=True)
